### ISSUE TITLE
此模块会导致tg自带的emoji输入变的卡顿

### ISSUE THREAD

**Issue by sharp-tasting** [thermatk/TgEmojiReplacer#1]
感谢开发者做出该模块，但用了这个模块之后出现了两个问题。tg自带的emoji输入变的卡顿，无法流畅的滑动emoji列表。卸载该模块后正常。
机型nexus 6，系统android 6.0.1，tg版本3.7.0。

**Comment by thermatk** [comment]
I felt this too, will try to understand why it might be so slow when i have time :+1:
