### ISSUE TITLE
Semi-broken on v3.12

### ISSUE THREAD

**Issue by dogtopus** [thermatk/TgEmojiReplacer#3]
With telegram 3.12 it seems that the dev team modified the emoji displaying code so this module no longer works in chats (stock telegram emojis are shown instead of android emojis). Emojis in usernames, chat list, etc. are still rendered as android emojis.

**Comment by thermatk** [comment]
true, but have no idea how exactly they changed it, as the source code is not published since 24th June :(

**Comment by evyd13** [comment]
You could decompile the apk file.

**Comment by GautierLePire** [comment]
It works with v3.13 🙌

**Comment by livingsilver94** [comment]
v3.13.1 and it's broken again 😀

**Comment by h3r0n** [comment]
> the source code is not published since 24th June :(

Telegram-FOSS has been updated to v3.13.1 last week. So the Telegram app is opensource again.

**Comment by thermatk** [comment]
In the new code there is an interesting line:
`if (MessagesController.getInstance().useSystemEmoji || cs == null || cs.length() == 0) {`
will investigate more if that's an option or can be triggered

**Comment by thermatk** [comment]
But with this preference boolean I also have a feeling the upstream code is being readied for an option like that 👍
