### ISSUE TITLE
Seems broken on 3.16.0

### ISSUE THREAD

**Issue by aphirst** [thermatk/TgEmojiReplacer#8]
Xposed is still installed and otherwise properly configured. I've done a couple of reboot cycles too.

I'm running Android 6.0.1 (CM13 milestone) with xposed version 87, Telegram ReEmoji 2.0, on an ARM64 ASUS Zenfone 2, though I suspect that doesn't matter.

Feel free to ask if there's anything else you want me to check or any further info you might need.

**Comment by thermatk** [comment]
Hi!
The Telegram guys shared that in 3.16 there are some new emojis, which means the asset files got changed and aren't compatible with my current build anymore. Until they share the [source of the new version of Telegram ](https://github.com/DrKLO/Telegram) there is nothing we can do. 
My approach to generate compatible asset files is here:
https://github.com/thermatk/TelegramEmojiGenerator
So, it's expected and good, if the module wouldn't respect the asset files version and replace them, you would end up seeing and sending not the emojis everyone else would be seeing in the same messages 👍

**Comment by aphirst** [comment]
Understood. I'll just hang fire, then. Thanks for the clarification, and I'll bear that in mind as a possible cause for if it happens another time.

**Comment by dogtopus** [comment]
Just let you know that the telegram android developer just pushed the latest code to github

**Comment by thermatk** [comment]
Fired up generator, let's see what changed there :+1:

**Comment by thermatk** [comment]
could someone test it:
https://github.com/thermatk/TgEmojiReplacer/releases/tag/3.0
before I publish to Xposed Repo? Don't have Xposed on my phone anymore
@dogtopus, @aphirst

**Comment by dogtopus** [comment]
Can confirm that it has regression on older (3.13) telegram. Only EmojiOne can be used regardless of my settings

**Comment by thermatk** [comment]
New version shouldn't work with v3.13 at all, that would be a bug :)
